<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_laporan_audit</name>
   <tag></tag>
   <elementGuidId>575560b9-1998-49b8-a9aa-c1617b5f2f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>fd8a06ef-f90b-4e82-843f-ecd76a03284e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading</value>
      <webElementGuid>617930f3-0b61-4e16-b87c-90889f25943d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Laporan Hasil Audit                </value>
      <webElementGuid>7c0d468b-deac-4cc0-89dd-b67d6b5d2428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content bg-gray-lighter&quot;]/div[@class=&quot;row items-push&quot;]/div[@class=&quot;col-sm-8&quot;]/h1[@class=&quot;page-heading&quot;]</value>
      <webElementGuid>200075de-f7c5-4393-8369-3c884bf6f442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div/div/div/h1</value>
      <webElementGuid>0c9cae96-edc5-4d57-9ea6-333e60d90d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kevin Romero'])[1]/following::h1[1]</value>
      <webElementGuid>7012525f-7c59-4f8f-999a-0a279d60346c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[4]/preceding::h1[1]</value>
      <webElementGuid>47fea8b5-01fc-4db2-984d-717cb5e2439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[5]/preceding::h1[1]</value>
      <webElementGuid>6df66c55-27a8-4003-81a1-2f17ab965af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>892c62bd-83ab-4340-b0cc-2f3101300a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                    Laporan Hasil Audit                ' or . = '
                    Laporan Hasil Audit                ')]</value>
      <webElementGuid>522e5b91-e4ad-4da0-94e6-0b4cf7905438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
