<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_supervisor</name>
   <tag></tag>
   <elementGuidId>b03f68e7-e297-447a-8514-325db7215ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group:nth-child(21) > select:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-supervisor-0q-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;(SLH) Slamet Rahayu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>948c3020-f8e3-41c9-993b-d6f65598dbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4582cc2e-074e-4067-a07b-e465dc48ebdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-supervisor-0q-container</value>
      <webElementGuid>f55d1121-f6c8-4300-b0e0-158fdd69608c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(SLH) Slamet Rahayu</value>
      <webElementGuid>8012afbc-b954-4ccc-9164-5ca70dcc7c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(SLH) Slamet Rahayu</value>
      <webElementGuid>0e2a89b8-3b45-41d7-817e-a191f934683f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-supervisor-0q-container&quot;)</value>
      <webElementGuid>95707619-8ef1-4d7e-a5b5-4c270afd3bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-supervisor-0q-container']</value>
      <webElementGuid>4888196f-05c0-4fe5-a000-2c09762e7a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[21]/span/span/span/span</value>
      <webElementGuid>747ee4bf-d17c-4f33-b87c-533594199828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisor'])[1]/following::span[4]</value>
      <webElementGuid>b439884c-f44f-4331-abeb-6399dded40ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(SWO) Siswo Pujono'])[2]/following::span[6]</value>
      <webElementGuid>ffc00efb-acb7-40f3-bf19-26af3e311214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketua Tim'])[1]/preceding::span[3]</value>
      <webElementGuid>66bd4620-2228-4686-9eca-12e9af9f3c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(TTR) Teguh Triana (Tim Ops Cabang Garut)'])[2]/preceding::span[3]</value>
      <webElementGuid>d41edbff-9b71-4974-a3c4-8161d1677682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/span/span/span/span</value>
      <webElementGuid>67be5869-8625-4882-ab49-32d073345d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-supervisor-0q-container' and @title = '(SLH) Slamet Rahayu' and (text() = '(SLH) Slamet Rahayu' or . = '(SLH) Slamet Rahayu')]</value>
      <webElementGuid>b797f517-791e-4ca4-b7e0-29e661f3caf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
