<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_operasional</name>
   <tag></tag>
   <elementGuidId>50a8b7a3-caee-452a-b0f6-39f73b9d7163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.js-select2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-category-r1-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Operasional (OPS) &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a09756b8-aa73-4c5a-b10e-bd68349b3351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b8a34180-6358-4ead-b7ec-96a51a741bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-category-r1-container</value>
      <webElementGuid>75d002d8-d05e-42c9-b2b3-7cf69b342e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Operasional (OPS) </value>
      <webElementGuid>ba157a25-0502-4cc6-9fe1-cf1064950ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operasional (OPS) </value>
      <webElementGuid>b366cadc-949c-40e0-8647-6406f7fe5d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-category-r1-container&quot;)</value>
      <webElementGuid>fb2e0601-8bd8-4456-8dbc-9d62e4254ace</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-category-r1-container']</value>
      <webElementGuid>b354557e-f853-4623-8685-dfbca23ed0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>9fbcbde0-bf62-4e52-bfc9-2b7fd35593e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::span[4]</value>
      <webElementGuid>4af28132-fc3a-4e68-bf19-ff760fe3f758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Surat Tugas'])[1]/following::span[4]</value>
      <webElementGuid>59a1d852-21f8-4967-8084-7e7688bd0465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Auditee'])[1]/preceding::span[3]</value>
      <webElementGuid>a3debee9-31a8-423c-a662-7ce0b75faf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/preceding::span[3]</value>
      <webElementGuid>13813edb-57ec-4df6-9367-32ccc5c9b31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>4a34a3d8-00d6-4b4c-981d-d385f6165d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-category-r1-container' and @title = 'Operasional (OPS) ' and (text() = 'Operasional (OPS) ' or . = 'Operasional (OPS) ')]</value>
      <webElementGuid>08db5927-9917-4330-8b44-30b3586b85d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
