<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_penanggung_jawab</name>
   <tag></tag>
   <elementGuidId>d31cee40-c223-492b-bbba-397a3b111281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group:nth-child(20) > select:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-penanggung_jawab-5z-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;(SWO) Siswo Pujono&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00cded5d-cf6e-4f55-b1a4-ed4aaf1f4755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ed1a6141-9dce-46b1-bea6-6caf2aab17c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-penanggung_jawab-5z-container</value>
      <webElementGuid>8105e09e-8a51-4794-bf70-d50c4e4baa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(SWO) Siswo Pujono</value>
      <webElementGuid>f27f7ee2-749f-4311-b9ca-6dcd3e3ec256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(SWO) Siswo Pujono</value>
      <webElementGuid>ddb35f3d-95ad-4150-a5f4-4de3f8d1b11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-penanggung_jawab-5z-container&quot;)</value>
      <webElementGuid>dc277297-e785-4a63-828e-c4139d1a3a95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-penanggung_jawab-5z-container']</value>
      <webElementGuid>82c7bf1a-a88d-4c72-ae35-ba90084c71d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[20]/span/span/span/span</value>
      <webElementGuid>cc845314-c915-4331-a686-be8b50a40529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penanggung Jawab'])[1]/following::span[4]</value>
      <webElementGuid>94ffd3ad-34cd-4862-8306-5d98fed9aab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTS'])[1]/following::span[4]</value>
      <webElementGuid>5e3268db-cc27-4d49-96d4-36df117162ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supervisor'])[1]/preceding::span[3]</value>
      <webElementGuid>d8160ce8-de2a-4f97-b9d3-6075561c1d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(SLH) Slamet Rahayu'])[2]/preceding::span[3]</value>
      <webElementGuid>88828bc1-c364-4be5-9f43-d097e935d557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/span/span/span/span</value>
      <webElementGuid>97de3021-ea49-4d54-91bc-b4c068eecef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-penanggung_jawab-5z-container' and @title = '(SWO) Siswo Pujono' and (text() = '(SWO) Siswo Pujono' or . = '(SWO) Siswo Pujono')]</value>
      <webElementGuid>fea3bf20-f5ee-4edb-8280-a9e6d31ef8c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
