<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_tipe_auditee</name>
   <tag></tag>
   <elementGuidId>1c2eda70-7a3e-489c-b82e-cc31bac930b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[value=&quot;1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'type_cabang']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='type_cabang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cabang&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cc56abd-d4f2-40fe-ad2e-811b1addd935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b8ecceec-048b-4c8b-a002-deb08bfc889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type_cabang</value>
      <webElementGuid>0084b56e-e11c-48a9-95d6-f68eaea1561a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${valueLocation}</value>
      <webElementGuid>88faaa31-5c0e-48bb-af78-8e3422154958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getCabang(this)</value>
      <webElementGuid>1078721f-cd79-44c1-b13d-5fb9166258c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content content-narrow&quot;]/form[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;block-content block-content-narrow&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;radio-inline&quot;]/input[1]</value>
      <webElementGuid>71e79b45-78f8-4d0f-af1d-a4573a437a17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='type_cabang']</value>
      <webElementGuid>06b30edf-bcc3-4a8f-8de1-38e811e403fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[2]/label[2]/input</value>
      <webElementGuid>afd943e9-3942-442b-ad38-5ba05ba5bd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>10a94121-8ca4-4a6f-80e1-c03643e99cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'type_cabang']</value>
      <webElementGuid>6b86677a-e1b1-4bb9-9eb9-dda5864f5bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
