<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_persetujuan_surat_tugas</name>
   <tag></tag>
   <elementGuidId>afd591bd-b0c9-49ff-88ca-3f6af951e4ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.open > ul:nth-child(2) > li:nth-child(2) > a:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-scroll']/div/div[2]/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Menunggu Persetujuan (Surat Tugas)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>beb42e2b-4675-4b8a-981d-e331f05724f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://10.61.3.37/PNM-SPI/member/surat_tugas/</value>
      <webElementGuid>2ce18abb-44d1-4775-b081-582e9b543f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menunggu Persetujuan (Surat Tugas)</value>
      <webElementGuid>2d443e02-b63e-426e-83ff-4e4cb23ad8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-scroll&quot;)/div[@class=&quot;sidebar-content&quot;]/div[@class=&quot;side-content&quot;]/ul[@class=&quot;nav-main&quot;]/li[@class=&quot;open&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>f4d0ddca-f4ee-4e1e-8f04-6cc66f843832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-scroll']/div/div[2]/ul/li/ul/li/a</value>
      <webElementGuid>62743441-6d09-495d-bc55-428df3296c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Menunggu Persetujuan (Surat Tugas)')]</value>
      <webElementGuid>e106b4d1-35a4-4fe5-99c8-a3f374bfe3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas'])[1]/following::a[1]</value>
      <webElementGuid>bb9e6d32-b5d3-4219-b1cb-f76509c3354b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept Surat Tugas Success'])[20]/following::a[4]</value>
      <webElementGuid>c8866478-666a-47b8-a644-22018d154863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siap di Print (Surat Tugas)'])[1]/preceding::a[1]</value>
      <webElementGuid>a9a9a6c0-3a55-4b98-9cf4-3db42fa6754d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori (Surat Tugas)'])[1]/preceding::a[2]</value>
      <webElementGuid>6a249b6d-f12d-4fd2-bd61-899c884c50b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menunggu Persetujuan (Surat Tugas)']/parent::*</value>
      <webElementGuid>c2305044-1d82-4e64-b238-419b5ac54c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://10.61.3.37/PNM-SPI/member/surat_tugas/']</value>
      <webElementGuid>2399d2a5-b259-45d3-afc1-a97183cb9105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>8bd7a0e5-5421-437a-bcd8-fdf6860669dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://10.61.3.37/PNM-SPI/member/surat_tugas/' and (text() = 'Menunggu Persetujuan (Surat Tugas)' or . = 'Menunggu Persetujuan (Surat Tugas)')]</value>
      <webElementGuid>2652e9c5-c55b-43bc-ba02-e5cd52737a8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
