<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_surat_tugas</name>
   <tag></tag>
   <elementGuidId>30447fdf-1e44-466e-a837-8f6d96c38153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.nav-main > li:nth-child(1) > a:nth-child(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'http://10.61.3.37/PNM-SPI/member/surat_tugas/' and (text() = 'Menunggu Persetujuan (Surat Tugas)' or . = 'Menunggu Persetujuan (Surat Tugas)')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-scroll']/div/div[2]/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Menunggu Persetujuan (Surat Tugas)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>141b419c-8fee-4056-a052-9dce84fd558e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://10.61.3.37/PNM-SPI/member/surat_tugas/</value>
      <webElementGuid>247a840a-d806-40ef-ac29-b2510b287ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menunggu Persetujuan (Surat Tugas)</value>
      <webElementGuid>09fc2673-6345-4a50-af7e-13fba2f21522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-scroll&quot;)/div[@class=&quot;sidebar-content&quot;]/div[@class=&quot;side-content&quot;]/ul[@class=&quot;nav-main&quot;]/li[@class=&quot;open&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>2614f8ba-6e55-4901-8d4f-d26d2187d228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-scroll']/div/div[2]/ul/li/ul/li/a</value>
      <webElementGuid>0a582f2e-868b-4501-a218-166cf1ea0f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Menunggu Persetujuan (Surat Tugas)')]</value>
      <webElementGuid>68dc5355-b78e-49d8-af34-7a048670d76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas'])[1]/following::a[1]</value>
      <webElementGuid>25df4c5e-1ee6-458d-99f4-b0ab2383e90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept Surat Tugas Success'])[20]/following::a[4]</value>
      <webElementGuid>64495748-7f3f-4d0d-8001-8a63cb7707cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siap di Print (Surat Tugas)'])[1]/preceding::a[1]</value>
      <webElementGuid>fdf2f504-3ac5-4f96-86c7-bf46b431aa38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori (Surat Tugas)'])[1]/preceding::a[2]</value>
      <webElementGuid>419b639e-947f-4150-9b3f-e83b4b2ec385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menunggu Persetujuan (Surat Tugas)']/parent::*</value>
      <webElementGuid>2ac12396-d227-4a2d-bc90-d8c17b111fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://10.61.3.37/PNM-SPI/member/surat_tugas/']</value>
      <webElementGuid>842c33e3-3136-4b7e-b236-9c269ba40f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>a0368704-f962-4735-953d-ddb047ea5f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://10.61.3.37/PNM-SPI/member/surat_tugas/' and (text() = 'Menunggu Persetujuan (Surat Tugas)' or . = 'Menunggu Persetujuan (Surat Tugas)')]</value>
      <webElementGuid>c4784067-fb92-4451-b903-3754f1dd3245</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
