<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>element_nomor_laporan</name>
   <tag></tag>
   <elementGuidId>4dade00a-0af1-4963-a2a9-29041e93ca48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.td-os-title.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;LR-052/PNM-SPI/II/2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4ba7e1d4-67b3-4628-9299-27d22a83b4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-os-title text-danger</value>
      <webElementGuid>20debdad-6ce9-4e22-8ecb-9a01a1007d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LR-052/PNM-SPI/II/2024</value>
      <webElementGuid>d8509c02-e0f6-4143-ad8f-43bb7fb8e5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-os-title text-danger&quot;]</value>
      <webElementGuid>de15058a-cf16-4e19-99b5-81731bb6f4d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td</value>
      <webElementGuid>2b3d5692-ab44-4631-bd85-efb21405fd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan Terakhir'])[1]/following::td[1]</value>
      <webElementGuid>1b791002-5113-465f-8791-bac88e5a82e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibuat oleh'])[1]/following::td[1]</value>
      <webElementGuid>e68b6d06-a478-4b2c-9139-0b3e9ea99479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIVISI DIVISI KEPATUHAN'])[1]/preceding::td[1]</value>
      <webElementGuid>046b9b52-b3e7-4560-a0b9-cba7d1cc6cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aulya Nurindrayani'])[1]/preceding::td[2]</value>
      <webElementGuid>d9d90b28-ec2c-470c-817d-2cd5dfc688c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LR-052/PNM-SPI/II/2024']/parent::*</value>
      <webElementGuid>2923663d-3b29-4c9c-a038-471a7a43522a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>77b52118-7f15-4f98-9e69-c004af3a341e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'LR-052/PNM-SPI/II/2024' or . = 'LR-052/PNM-SPI/II/2024')]</value>
      <webElementGuid>ba91d537-6622-410c-8691-8c8d76300d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
