<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_laporan_hasil_audit</name>
   <tag></tag>
   <elementGuidId>dbad6ff5-312b-4464-a211-bc2568f67070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b06fad55-4312-422d-9b9c-815946a0dea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading</value>
      <webElementGuid>b8d4265b-1b3a-4b1f-89e6-a74abec75c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Laporan Hasil Audit                </value>
      <webElementGuid>e70a9ca8-76c0-45b1-9fe5-ab0039a587f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content bg-gray-lighter&quot;]/div[@class=&quot;row items-push&quot;]/div[@class=&quot;col-sm-8&quot;]/h1[@class=&quot;page-heading&quot;]</value>
      <webElementGuid>e0cc4fe5-53e6-42bb-8ee6-164aee83d892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div/div/div/h1</value>
      <webElementGuid>f5c2eeac-0b23-4fa4-adad-09fb6857c462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kevin Romero'])[1]/following::h1[1]</value>
      <webElementGuid>75ada739-52a6-4867-a7a1-c2b99cc6bcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[4]/preceding::h1[1]</value>
      <webElementGuid>a8aac3cb-2367-47e3-ae36-753171ee4ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[5]/preceding::h1[1]</value>
      <webElementGuid>224f4236-04c0-4b6f-8975-7c19d80b0480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>e9ed760b-7d63-4cf8-932d-b8646b7189d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                    Laporan Hasil Audit                ' or . = '
                    Laporan Hasil Audit                ')]</value>
      <webElementGuid>3b505838-418a-412a-b7d9-83bb89bec3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
