<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_editor_italic</name>
   <tag></tag>
   <elementGuidId>46d3e649-33d0-48b2-bf60-08fe4a1a2ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.note-style > button:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20850d41-e67d-4af4-baa4-62f0fba3db88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70d441ad-87ff-4159-9e70-e0bea48322e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm btn-small active</value>
      <webElementGuid>50375867-b223-4a62-97cb-7c3d9d0f5f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>16121c75-bd03-4c89-b32c-e081bf51a939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>39e481fc-b8b4-4e45-978d-0b6a8a508778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>1809e7a7-d107-48d4-a475-4eb0e0568675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ui-id-10</value>
      <webElementGuid>3063371b-3e85-49fb-8b63-8829a43e7ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content content-narrow&quot;]/form[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;block-content block-content-narrow&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;note-editor&quot;]/div[@class=&quot;note-toolbar btn-toolbar&quot;]/div[@class=&quot;note-style btn-group&quot;]/button[@class=&quot;btn btn-default btn-sm btn-small active&quot;]</value>
      <webElementGuid>efcb8d56-a71b-4758-b111-78fc159c8198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>5414d007-29c2-4c6b-9685-1273629844c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[4]/div/div[5]/div/button</value>
      <webElementGuid>f09f7856-f54f-4164-ae64-a640c3204582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.google.com'])[1]/following::button[14]</value>
      <webElementGuid>87aab534-2216-44a2-acc2-7d38a51cb0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues'])[1]/following::button[14]</value>
      <webElementGuid>7c561292-776a-45fb-af2d-cba6bc844242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background Color'])[1]/preceding::button[10]</value>
      <webElementGuid>1da53468-52d8-4da2-91b3-f84efb44f10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set transparent'])[1]/preceding::button[10]</value>
      <webElementGuid>13961c8a-4318-4b75-adf3-0891376649e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>1c110882-b21c-4ffc-89d9-fa7a1b617f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>8c491ddd-87b6-4916-a4ca-158722d460ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
