<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_editor_underline</name>
   <tag></tag>
   <elementGuidId>ca002157-904d-4a6e-a09e-13a414d6a023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.note-style > button:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c68d2fa8-407a-4b6e-99e4-1fdbeb9c4db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4831e1b4-b233-4a11-ba13-bd0e37fb38ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm btn-small active</value>
      <webElementGuid>df3f1b5c-043e-4a3b-81de-00a1d9f106fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>50c3f45a-5ea1-4456-a1ef-ac793e5ab715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4f0fdade-9215-498d-ac11-353367f748d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>475f76b4-f3d2-43cc-8603-cc4e1a781b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ui-id-10</value>
      <webElementGuid>b899f8ac-e001-4116-b287-dcaa2e0fd495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content content-narrow&quot;]/form[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;block-content block-content-narrow&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;note-editor&quot;]/div[@class=&quot;note-toolbar btn-toolbar&quot;]/div[@class=&quot;note-style btn-group&quot;]/button[@class=&quot;btn btn-default btn-sm btn-small active&quot;]</value>
      <webElementGuid>75629b48-29fd-41cb-81ba-5e642bab8a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>768b0dbe-92c6-4e54-8245-b4fdf99b44f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[4]/div/div[5]/div/button</value>
      <webElementGuid>560484fa-f6be-446e-9880-5283be2e047e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.google.com'])[1]/following::button[14]</value>
      <webElementGuid>63aec622-32e6-4c36-b64d-bb226f74488a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues'])[1]/following::button[14]</value>
      <webElementGuid>a1f3db99-0c81-4305-8373-38763137c64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Background Color'])[1]/preceding::button[10]</value>
      <webElementGuid>7b8f0852-06e1-4821-9b7a-29fd5c0c1774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set transparent'])[1]/preceding::button[10]</value>
      <webElementGuid>0128daee-8603-4771-beaa-c69a9108c1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>d071799a-623d-44e5-bd09-e3fdf3a1b54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>b365b3a5-9124-4168-a58a-761721cd25a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
