<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toolbar_text_editor</name>
   <tag></tag>
   <elementGuidId>d3e5b228-1a6b-47a8-ab25-57d4b1e39142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.note-toolbar.btn-toolbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[4]/div/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f93e2df7-fce0-48da-a0bf-fc22cc65357a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-toolbar btn-toolbar</value>
      <webElementGuid>157daa82-c5f0-45c9-aa75-9d37ca247430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11  8 9 10 11 12 14 18 24 36 Background ColorSet transparentForeground ColorReset to default   1 x 1 </value>
      <webElementGuid>7378037c-fd9d-42a6-a141-77e107ab863f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content content-narrow&quot;]/form[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;block-content block-content-narrow&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;note-editor&quot;]/div[@class=&quot;note-toolbar btn-toolbar&quot;]</value>
      <webElementGuid>692f3e09-06c4-4519-ad24-e6e76a9a957b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[4]/div/div[5]</value>
      <webElementGuid>7297b358-f732-4e4c-8dc2-9207f73b4fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.google.com'])[1]/following::div[9]</value>
      <webElementGuid>9ababf4d-d550-421e-a3d9-01967add8772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues'])[1]/following::div[21]</value>
      <webElementGuid>43612d0b-acf0-4f3d-a9df-7c89ea69fafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[5]</value>
      <webElementGuid>d1a39c34-a84a-4aff-997b-54eced6213ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '11  8 9 10 11 12 14 18 24 36 Background ColorSet transparentForeground ColorReset to default   1 x 1 ' or . = '11  8 9 10 11 12 14 18 24 36 Background ColorSet transparentForeground ColorReset to default   1 x 1 ')]</value>
      <webElementGuid>926a2889-7245-4aa7-97d2-fc9dc5facc93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
