<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_upload_file_lha</name>
   <tag></tag>
   <elementGuidId>d47b25c1-293a-4cc5-ade5-5f03b65be331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9465066-1a8c-4b39-a692-a8a65b886821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2e199780-2c15-4e49-bf8f-1381ec8d9774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a64aee09-5ef2-4820-9db7-40376d601c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e7847923-b88b-4cf9-a39c-7c05e71bd5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content content-narrow&quot;]/form[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-12&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;block-content block-content-narrow&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3ec6cc5f-cd66-482f-8ca8-cfc98f6f0d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='file']</value>
      <webElementGuid>2d1e35dc-5937-4fa1-8d59-5ebcad07ee6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[3]/input</value>
      <webElementGuid>74b27270-fcd8-4d90-968b-184dd2505a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>95cbe009-d329-4cf0-ad11-07a6ebe300ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'file']</value>
      <webElementGuid>c634b525-b8ee-460c-8d8f-5adb8685891a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
