<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_detail_lha</name>
   <tag></tag>
   <elementGuidId>692476d5-9d01-43ae-a983-7c869d4b3cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>ec231f1a-0036-4c13-9a4c-e8a1483cf3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading</value>
      <webElementGuid>86ec4798-30f4-45d0-8b65-9368a8391669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Detail Laporan Hasil Audit                </value>
      <webElementGuid>5a40bc07-e731-4ef6-9159-85b8957790a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content bg-gray-lighter&quot;]/div[@class=&quot;row items-push&quot;]/div[@class=&quot;col-sm-8&quot;]/h1[@class=&quot;page-heading&quot;]</value>
      <webElementGuid>21e74058-eb08-4803-9629-3586fd128fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div/div/div/h1</value>
      <webElementGuid>a833fa33-495f-49b3-bf7d-58628e2f8062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kevin Romero'])[1]/following::h1[1]</value>
      <webElementGuid>4ed0a6ff-3609-4eb9-984e-1b5f864d0c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas'])[2]/preceding::h1[1]</value>
      <webElementGuid>643ab4cd-7bc7-4ad5-9965-452b7b86cbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[3]/preceding::h1[1]</value>
      <webElementGuid>848a6530-1957-4925-88a9-c5ba3b333ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail Laporan Hasil Audit']/parent::*</value>
      <webElementGuid>65b28072-40fc-487a-8bbd-fbe1acbc942d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7d4af632-e755-46ca-8ccc-308845007506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                Detail Laporan Hasil Audit                ' or . = '
                Detail Laporan Hasil Audit                ')]</value>
      <webElementGuid>2e032b22-54b4-4531-8c9e-c55502d97d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
