<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_tambah_surat_tugas</name>
   <tag></tag>
   <elementGuidId>f10a21f4-d16a-469a-803d-1a8e159ed82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-container']/div[2]/div/div/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Tambah Surat Tugas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c52a5f43-ebd9-471f-bd1a-49f2698ade81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>0ce53ca2-7892-4335-9033-322bb8b1d1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://10.61.3.37/PNM-SPI/member/surat_tugas/home/insert/</value>
      <webElementGuid>8329a668-d33a-4736-9dfd-c13303ec39d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Tambah Surat Tugas                            </value>
      <webElementGuid>cf969ec8-1a08-4026-8a98-d8f3b6a6b236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;block-header&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;btn btn-sm btn-success&quot;]</value>
      <webElementGuid>56c73b36-55e0-4901-bbd4-e5dee522cf81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/div/div/div/div/div[3]/a</value>
      <webElementGuid>d92b1adf-37a0-49af-8e5e-d11384bbbb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::a[1]</value>
      <webElementGuid>c42e0fd5-bd02-4b87-b054-056ae18106c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Tahun:'])[1]/following::a[1]</value>
      <webElementGuid>9e02f440-e109-4119-8796-0b0d6f371066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::a[1]</value>
      <webElementGuid>0f6c3350-15d2-4a04-9997-f76adf04ef5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Surat Tugas'])[1]/preceding::a[1]</value>
      <webElementGuid>002a8611-7817-4180-a3fc-6f690e94db07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Surat Tugas']/parent::*</value>
      <webElementGuid>08415874-361e-4c57-93bc-a97a712294a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://10.61.3.37/PNM-SPI/member/surat_tugas/home/insert/']</value>
      <webElementGuid>28e887eb-c0b9-431d-b254-61848cce54b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>1590ffa0-caa5-4ff4-9942-3dc0fabf0441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://10.61.3.37/PNM-SPI/member/surat_tugas/home/insert/' and (text() = '
                                 Tambah Surat Tugas                            ' or . = '
                                 Tambah Surat Tugas                            ')]</value>
      <webElementGuid>f2d2d5f7-632d-4102-9df1-f8d78c64079e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
