<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_ketua_tim</name>
   <tag></tag>
   <elementGuidId>93675d96-19a2-4c43-b52f-b1f852f83e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ketua_tim-vw-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group:nth-child(22) > select:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;(TTR) Teguh Triana (Tim Ops Cabang Garut)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d63b855-011f-4cf2-a336-dc0471b9bd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b640e306-b060-4a92-957c-510978576b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ketua_tim-vw-container</value>
      <webElementGuid>79558857-98e6-4ac3-892a-5f5c2657fe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(TTR) Teguh Triana (Tim Ops Cabang Garut)</value>
      <webElementGuid>5b45ab64-2b93-4243-be36-76188148b3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(TTR) Teguh Triana (Tim Ops Cabang Garut)</value>
      <webElementGuid>cdcdd04d-b516-4be3-855d-7cdea2a6ef94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ketua_tim-vw-container&quot;)</value>
      <webElementGuid>c156d518-acac-44a4-9553-4d325b1c54f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ketua_tim-vw-container']</value>
      <webElementGuid>01fa87bb-fe42-4149-83ec-28654cff25ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div[22]/span/span/span/span</value>
      <webElementGuid>ff9f6216-3fa1-4745-b8e1-479247af9b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketua Tim'])[1]/following::span[4]</value>
      <webElementGuid>d67dde6c-c2e1-4fa1-b4f9-dd118d78aad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(SLH) Slamet Rahayu'])[2]/following::span[6]</value>
      <webElementGuid>b0282c87-d40b-4e9b-8fcc-4e419ab27dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan Kaki'])[1]/preceding::span[3]</value>
      <webElementGuid>2ccab0e8-970d-4573-b2b6-3667cca7e137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rich Text Editor, js-ckeditor-3'])[1]/preceding::span[3]</value>
      <webElementGuid>c414888a-e0b9-444a-bcb2-07d30e484dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/span/span/span/span</value>
      <webElementGuid>26da3df8-e9da-4cc4-9a70-790248f06fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ketua_tim-vw-container' and @title = '(TTR) Teguh Triana (Tim Ops Cabang Garut)' and (text() = '(TTR) Teguh Triana (Tim Ops Cabang Garut)' or . = '(TTR) Teguh Triana (Tim Ops Cabang Garut)')]</value>
      <webElementGuid>92760274-7416-40df-a142-67b88618b91c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
