<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tambah Surat Tugas</name>
   <tag></tag>
   <elementGuidId>50926582-d6de-4cf3-80e6-55e7eef4bcbe</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.js-select2</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='.js-select2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'select2-selection select2-selection--single' and @id = 'select2-surat_tugas-6j-container' and @title = 'Tambah Surat Tugas' and (text() = 'Tambah Surat Tugas' or . = 'Tambah Surat Tugas')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Tambah Surat Tugas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd3b6522-7183-4637-817b-44a814ad9f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single</value>
      <webElementGuid>8c4ad534-a777-49c3-8c34-272e7e8c38af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-surat_tugas-6j-container</value>
      <webElementGuid>d9589af4-2996-430f-90f0-e43009297b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tambah Surat Tugas</value>
      <webElementGuid>4eef26cd-d97d-4626-8ac5-1a56375effc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Surat Tugas</value>
      <webElementGuid>ed367bd2-e2f6-4913-83f9-66d153bf5024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-surat_tugas-6j-container&quot;)</value>
      <webElementGuid>8c22d851-b831-4288-ab29-4bacf6236ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-surat_tugas-6j-container']</value>
      <webElementGuid>9e8470f3-b7e4-4f10-aa32-85ec1a5d212d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-container']/div[2]/form/div/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>47ed1cc1-587e-4955-aa9e-20d60d780e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas'])[3]/following::span[4]</value>
      <webElementGuid>f4baa663-775f-4860-8452-62802dec095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Surat Tugas'])[1]/following::span[4]</value>
      <webElementGuid>0ef95891-4468-4e60-a025-410475571a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>92300168-2536-4e07-855d-2e72c722a69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-surat_tugas-6j-container' and @title = 'Tambah Surat Tugas' and (text() = 'Tambah Surat Tugas' or . = 'Tambah Surat Tugas')]</value>
      <webElementGuid>2745bbf9-4630-4e36-aec5-1f93beddb4d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
