<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_aksi_tabel_cetak</name>
   <tag></tag>
   <elementGuidId>7a319ea3-41d7-47c1-a051-b8f158d91083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>499ce05b-e06f-4056-998b-5e7addfcc119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>0fe6150e-8144-4d40-80a2-316d21db5fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://10.61.3.37/PNM-SPI/member/template/Home/prints/SuratTugas/ST240313007</value>
      <webElementGuid>bc83bbb7-6c49-4295-a4c7-f5326d203e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>48ed0296-4a48-44d1-97d9-7505ab4625b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cetak</value>
      <webElementGuid>9c589032-cdcd-44d7-9626-ea208361d44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[10]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>ed92eb7f-8678-407c-94af-bb78381a2c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[10]/a</value>
      <webElementGuid>050f354c-077e-415d-abf1-c0726c83ef78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cetak')]</value>
      <webElementGuid>4da67bf7-1aa6-477f-81e4-e7f4506ae800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[4]/following::a[1]</value>
      <webElementGuid>89faf314-5dbc-4b71-a4b4-e8bc24f1ba27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siap di Print'])[1]/following::a[2]</value>
      <webElementGuid>b8420b64-c061-45c7-be75-cc57cea40d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ST-085/PNM-AOV-OPS/II/2024'])[1]/preceding::a[1]</value>
      <webElementGuid>a06014fc-7975-44a2-ba63-6268fe180497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ULAMM GRESIK'])[1]/preceding::a[1]</value>
      <webElementGuid>1b05538a-db11-4bf2-8725-41061cec55ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cetak']/parent::*</value>
      <webElementGuid>6ee9cdb9-5158-418f-a7c9-a28bc5d1a5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://10.61.3.37/PNM-SPI/member/template/Home/prints/SuratTugas/ST240313007']</value>
      <webElementGuid>31a8c238-a148-41a3-8572-3e4accfe25cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/a</value>
      <webElementGuid>6cefa6ce-0586-429e-b3b4-efe7e5a1de64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://10.61.3.37/PNM-SPI/member/template/Home/prints/SuratTugas/ST240313007' and (text() = 'Cetak' or . = 'Cetak')]</value>
      <webElementGuid>f6f517b9-f83c-43cd-928c-a164678e7e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
