<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_item_table_lihatlaporan</name>
   <tag></tag>
   <elementGuidId>ac54f049-765a-490a-b009-0b820333d781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/main/div[2]/div/div/div/div[2]/div/div/div[2]/div/table/tbody/tr[1]/td[9]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>html body div#page-container.sidebar-l.sidebar-o.side-scroll.header-navbar-fixed main#main-container div.content div.row div.col-xs-12 div.block div.block-content div.table-responsive div#DataTables_Table_0_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer div.row div.col-sm-12 table#DataTables_Table_0.table.datatable.table-striped.dataTable.no-footer tbody tr.odd td div.btn-group.open button.btn.btn-info.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02c6741f-9cc7-487f-8f20-e3d868731f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info dropdown-toggle</value>
      <webElementGuid>b70cf8d9-dcf8-436f-b923-c3d95308de48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>b82a4361-d580-47c0-b2af-0c82389922da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28a401bf-8692-47cd-8379-fd336dc171c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[9]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-info dropdown-toggle&quot;]</value>
      <webElementGuid>928e0b97-d9a2-4693-8e2b-a040561b5d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[9]/div/button</value>
      <webElementGuid>ef1e30d5-f956-491e-a914-757d4d9556e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siap di Print'])[1]/following::button[1]</value>
      <webElementGuid>c67bd31f-1565-47b7-a66e-6ebdd20f91ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ULAMM MANUKAN SURABAYA'])[1]/following::button[1]</value>
      <webElementGuid>c1364832-1602-4bf6-99fe-55a9d524b64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Hasil Audit'])[4]/preceding::button[1]</value>
      <webElementGuid>577cf181-71ec-4d9a-83af-1019ed10fa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/preceding::button[1]</value>
      <webElementGuid>50e8d3e9-a642-449d-83ee-636caabaf28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/button</value>
      <webElementGuid>9139e0db-d506-47a4-83a7-9448fa753b9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
