<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sidemenu</name>
   <tag></tag>
   <elementGuidId>cb9438f5-2cc1-4cf6-a388-241316ec5027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.side-header.side-content.bg-white-op</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-scroll']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sidebar-scroll div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aeeffe76-18f0-4b67-9b47-28dc8c0586ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-header side-content bg-white-op</value>
      <webElementGuid>cfdcb2ec-425d-4c97-baa8-7089d5c94284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-scroll&quot;)/div[@class=&quot;sidebar-content&quot;]/div[@class=&quot;side-header side-content bg-white-op&quot;]</value>
      <webElementGuid>38b768f8-adeb-4005-9a2b-a7a9960f15fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-scroll']/div/div</value>
      <webElementGuid>faf79a4d-f23f-4927-95d5-29e01c4aa601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert Surat Tugas Success'])[7]/following::div[5]</value>
      <webElementGuid>b38d804e-fa20-449a-b913-0988a56f511f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert Tim Audit Success'])[6]/following::div[7]</value>
      <webElementGuid>055cbe0f-c31a-4f75-8e99-259ee87d27d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas'])[1]/preceding::div[1]</value>
      <webElementGuid>4353b87f-2356-449e-915d-b63c053b445e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu Persetujuan (Surat Tugas)'])[1]/preceding::div[1]</value>
      <webElementGuid>c6df8bc5-11ed-46db-9a69-313f343e3700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div</value>
      <webElementGuid>8b130219-f86f-480c-838d-2a8dd61d9ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
